const dummyData2 = {
    tordata: {
        '123' : [{
            matchid: '123_a',
            teamA: 'lions',
            teamB: 'sheeps',
            scoreTeanA: '1',
            scoreTeanB: '0',
            betTeanA: '1',
            betTeanB: '0',
            dateStart: '11/11/3000',
            score: '3',
        },
        {
            matchid: '123_b',
            teamA: 'ducks',
            teamB: 'sheeps',
            scoreTeanA: '1',
            scoreTeanB: '0',
            betTeanA: '1',
            betTeanB: '0',
            dateStart: '11/11/3000',
            score: '3',
        },
        {
            matchid: '123_c',
            teamA: 'mice',
            teamB: 'lions',
            scoreTeanA: '1',
            scoreTeanB: '0',
            betTeanA: '1',
            betTeanB: '0',
            dateStart: '11/11/3000',
            score: '3',
        }
        ],
        '345' : [{
            matchid: '345_a',
            teamA: 'lions',
            teamB: 'mice',
            scoreTeanA: '1',
            scoreTeanB: '0',
            betTeanA: '1',
            betTeanB: '0',
            dateStart: '11/11/3000',
            score: '3',
        }],
        '678' : [{
            matchid: '678_a',
            teamA: 'lions',
            teamB: 'sheeps',
            scoreTeanA: '1',
            scoreTeanB: '0',
            betTeanA: '1',
            betTeanB: '0',
            dateStart: '11/11/3000',
            score: '3',
        }],
        '901' : [{
            matchid: '901_a',
            teamA: 'lions',
            teamB: 'sheeps',
            scoreTeanA: '1',
            scoreTeanB: '0',
            betTeanA: '1',
            betTeanB: '0',
            dateStart: '11/11/3000',
            score: '3',
        }],
    }
}
export default dummyData2